apiVersion: v1alpha1
kind: Setting
metadata:
  name: Summer-Cat-setting
spec:
  forms:
    - group: base
      label: 基本设置
      formSchema:
        - $formkit: attachment
          name: banner
          label: 首页背景图
          value: https://s2.loli.net/2024/05/29/cflPL7R4NJaQm1A.jpg
        - $formkit: attachment
          name: favicon
          label: 主题favicon
          help: 注意：[Halo >> 设置 >> favicon]优先级更高
          value: https://s2.loli.net/2024/05/29/YeBxEhvcPzpmD8u.png
    - group: beian
      label: 备案信息
      formSchema:
        - $formkit: text
          name: icp_text
          label: ICP备案号
          placeholder: "请输入ICP备案号"
        - $formkit: text
          name: icp_link
          label: ICP备案跳转链接
          value: https://beian.miit.gov.cn/
