apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: nirvana
spec:
  displayName: 涅槃
  description: 涅槃涅了一捏捏
  logo: https://halo.run/logo
  repo: https://github.com/PG-Z/nirvana.git
  author:
    name: evan
    website: https://aifeel.top
  website: https://github.com/halo-sigs/theme-foo
  settingName: "nirvana-setting"
  configMapName: "nirvana-configMap"
  version: 1.0.0
  require: 2.0.0
