apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: Summer-Cat
spec:
  displayName: 喵喵叫
  description: single column halo theme
  logo: https://cdn.aifeel.top/typora/Playful%20cat-bro.png
  repo: https://github.com/PG-Z/Summer-Cat.git
  author:
    name: evan
    website: https://aifeel.top
  website: https://aiheiyo.top
  settingName: "Summer-Cat-setting"
  configMapName: "Summer-Cat-configMap"
  version: 1.2.3.alpha
  require: 2.15.0
